### ISSUE TITLE
Missing artifact (canvas_forward_http.tgz)

### ISSUE THREAD

**Issue by pillows** [canvasnetworks/canvas#2]
https://s3.amazonaws.com/canvas-public-artifacts/canvas_forward_http.tgz

Since we don't have the S3 anymore, we don't have access to this file.

**Comment by TimothyFitz** [comment]
I'm asking around to see if we have a copy of that. It may not work on the past couple of OS Xs anyway.

It was a binary that when run locally mapped port 80 -> 9000 and port 443 -> 9001. You could do the same thing via pfctl. This allows the sandbox server to run as your user instead of root, which vastly simplifies permissions for developers.

**Comment by ctrlcctrlv** [comment]
god what the fuck

**Comment by ctrlcctrlv** [comment]
to leave a more serious comment:

so @TimothyFitz here's the issue right

if that is all that that code did then no one would go to the trouble of making an nginx extension to map the port

http://nginx.org/en/docs/http/ngx_http_proxy_module.html

this extension has existed since the beginning of the project

so, all you would have had to do is—

```nginx
location / {
    proxy_pass http://127.0.0.1:PORT$request_uri;
}
```

right.

so am i to believe a developer would be so blind as to not notice this obvious feature that they write an entire module

_or_, am i to assume that this company did not release its source code properly

btw i own the aws bucket now
